export const DOG_BREEDS = [
  'Mestizo',
  'Labrador Retriever',
  'Golden Retriever',
  'Caniche (Poodle)',
  'Bulldog Francés',
  'Bulldog Inglés',
  'Chihuahua',
  'Pug',
  'Beagle',
  'Boxer',
  'Cocker Spaniel',
  'Dálmata',
  'Dóberman',
  'Pastor Alemán',
  'Pastor Belga',
  'Border Collie',
  'Collie',
  'Rottweiler',
  'Schnauzer',
  'Schnauzer Mini',
  'Yorkshire Terrier',
  'Shih Tzu',
  'Maltés',
  'Pomerania',
  'Husky Siberiano',
  'Akita',
  'Shiba Inu',
  'Basset Hound',
  'Galgo',
  'Whippet',
  'Bull Terrier',
  'American Staffordshire Terrier (Pitbull)',
  'Staffordshire Bull Terrier',
  'Gran Danés',
  'San Bernardo',
  'Bernés de la Montaña',
  'Mastín Napolitano',
  'Dogo Argentino',
  'Setter Irlandés',
  'Pointer',
  'Weimaraner',
  'Bichón Frisé',
  'Bichón Maltés',
  'Cavalier King Charles Spaniel',
  'Salchicha (Dachshund)',
  'Jack Russell Terrier',
  'Fox Terrier',
  'West Highland White Terrier',
  'Carlino',
  'Chow Chow',
  'Samoyedo',
  'Lebrel Afgano',
  'Pequinés',
  'Spitz',
  'Otra',
] as const;
