-- ============================================================
-- Match suggestions between a "lost" post and a "found" post
-- Generated by an Edge Function when a new post is created
-- (see ADR-005) — never resolved automatically, only suggested.
-- ============================================================

create table public.match_suggestions (
  id            uuid primary key default gen_random_uuid(),
  lost_post_id  uuid not null references public.dog_posts(id) on delete cascade,
  found_post_id uuid not null references public.dog_posts(id) on delete cascade,
  distance_km   numeric(6,2) not null,
  status        text not null default 'suggested'
    check (status in ('suggested', 'dismissed', 'confirmed')),
  created_at    timestamptz not null default now(),
  constraint match_suggestions_unique unique (lost_post_id, found_post_id)
);

-- ============================================================
-- RLS
-- ============================================================

alter table public.match_suggestions enable row level security;

-- readable/updatable by the authors of either post in the pair
create policy "match_suggestions_select_participant" on public.match_suggestions
  for select using (
    exists (
      select 1 from public.dog_posts
      where id in (lost_post_id, found_post_id) and user_id = auth.uid()
    )
  );

create policy "match_suggestions_update_participant" on public.match_suggestions
  for update using (
    exists (
      select 1 from public.dog_posts
      where id in (lost_post_id, found_post_id) and user_id = auth.uid()
    )
  );
